### ISSUE TITLE
Couple things about the rules in scalariform

### ISSUE THREAD

**Issue by dbtsai** [scala-ide/scalariform#102]
We're trying to use scalariform to format Apache Spark project to have unified codebase. 

Some of the default rules don't match our coding style, and we're trying to find if we can customize those rules without luck. 

Is there a way to specify the line width? 

Curly braces in imports shouldn't be forced to have spaces separating them. E.g. import org.apache.spark.{ RDD, SparkContext }

Is there a way to force the function parameter declaration to indent 4 spaces rather than 2?

Thanks.

**Comment by jkinkead** [comment]
Parameter indent is handled with `doubleIndentMethodDeclaration`; long lines tracked elsewhere; spacing handled with `spacesAroundMultiImports`. Closing.
