### ISSUE TITLE
Jar download link broken

### ISSUE THREAD

**Issue by mpollmeier** [scala-ide/scalariform#112]
this is referenced from the readme but is broken:
https://s3.amazonaws.com/scalariform/scalariform.jar

**Comment by jawshooah** [comment]
:+1: for a GitHub release. This would also enable package managers like [Homebrew](https://github.com/Homebrew/homebrew) to support scalariform.

**Comment by godenji** [comment]
Now available as of 0.2.1 release (see [releases](https://github.com/scala-ide/scalariform/releases/tag/0.2.1))
