### ISSUE TITLE
Automatic new line at the end of file

### ISSUE THREAD

**Issue by ppiotrow** [scala-ide/scalariform#113]
I think the current version doesn't allow that feature. It will satisfy my git repository if you could add this.

**Comment by jkinkead** [comment]
I have a patch for this - should it be the default, or should it be an option? @sschaef / @fommil ?

**Comment by sschaef** [comment]
It needs to be optional. We need to stay backwards compatible.

**Comment by jkinkead** [comment]
Great. Feel free to assign to me if you like - I'll put in a patch shortly.

**Comment by fommil** [comment]
@jkinkead thank for for all your recent work on scalariform, it really needed a hero to come along and get it moving again! :smile:

**Comment by fommil** [comment]
@jkinkead FYI this is the goal for 1.0 https://github.com/scala-ide/scalariform/milestones/1.0 and might answer your question above. Backwards compatibility is absolutely **mission criticial**. It can impact teams upgrading their IDE, with scalariform regressions becoming major operational issues.

**Comment by jkinkead** [comment]
Thank **you** for taking charge of this project! I don't have the time to do the real project maintenance work - but I'm happy to contribute patches! We use this a ton at [AI2](http://allenai.org/), and it's great to have regular releases being made again . . . that I'm not in charge of. ;)
