### ISSUE TITLE
Indent expressions on RHS of a <- in for expressions

### ISSUE THREAD

**Issue by ajknoll** [scala-ide/scalariform#123]
Currently, the following:

``` .scala
_ <-
  if (cond)
    thing
  else
    other
```

reformats to the following, which gives the visual impression that the `else` is a subsequent step in the sequence:

``` .scala
_ <- if (cond)
  thing
else
  other
```

Optimally it should resolve to the original, but at the very least it should be indented forward on lines after the first, i.e.:

``` .scala
_ <- if (cond)
    thing
  else
    other
```

**Comment by godenji** [comment]
Workaround:
```
_ <- (
  if (cond)
    thing
  else
    other
)
```
