### ISSUE TITLE
dependency when using Scalariform as a library

### ISSUE THREAD

**Issue by bdkent** [scala-ide/scalariform#124]
The documentation on the [Library](https://github.com/mdr/scalariform/wiki/Library) wiki page no longer seems accurate for projects using Scala 2.11.x.

I am upgrading a project from Scala 2.10 to 2.11 and the sbt configuration `libraryDependencies += "org.scalariform" %% "scalariform" % "0.1.4"` no longer works.

I don't see a scalariform artifact of `scalariform_2.11` in [maven](http://mvnrepository.com/artifact/org.scalariform). Is Scalariform hosted in a different repository now?

**Comment by godenji** [comment]
Library wiki updated to reflect latest version (0.2.1)
