### ISSUE TITLE
Download link for `scalariform.jar` gives an access error

### ISSUE THREAD

**Issue by Gabriel439** [scala-ide/scalariform#128]
I was trying to set up scalariform with vim and the README directs me to this download link:

https://s3.amazonaws.com/scalariform/scalariform.jar

However, if I visit that link I get an access error from S3, specifically "All access to this object has been disabled"

**Comment by godenji** [comment]
@Gabriel439 you've probably returned to Haskell land, but in the event you still use this library, latest release is under the 0.2.1 tag in the [releases page](https://github.com/scala-ide/scalariform/releases/tag/0.2.1)

**Comment by Gabriel439** [comment]
Yeah, but it's still appreciated nonetheless :)
