### ISSUE TITLE
preserveDanglingCloseParenthesis support for method signatures

### ISSUE THREAD

**Issue by david-bouyssie** [scala-ide/scalariform#129]
preserveDanglingCloseParenthesis  is a cool feature but it does not seem to work for method signatures

Example:
```scala
def sum(
  a: Float,
  b: Float
): Float
```
will be formatted to
```scala
def sum(
  a: Float,
  b: Float): Float
```

**Comment by ChrisNeveu** [comment]
This is also the case for class declarations where
```scala
case class Foo(
   property1 : String,
   property2 : String
) extends SomeLongClassName
```
is formatted to

```scala
case class Foo(
   property1 : String,
   property2 : String) extends SomeLongClassName
```
even with `preserveDanglingCloseParenthesis` enabled.

**Comment by hzwaal** [comment]
+1

**Comment by jkinkead** [comment]
This should work with the new `danglingCloseParenthesis` option.

**Comment by david-bouyssie** [comment]
Do you have updated the code related to this option ?
I'm using the Scala IDE 4.30 and this behavior is still here when I format the code.

**Comment by sschaef** [comment]
Scala IDE still uses an older version of scalariform and this won't change until a new version of scalariform is released.

**Comment by david-bouyssie** [comment]
Ok. Thank you for the fix !
