### ISSUE TITLE
Can you add a new collaborator to this repository?

### ISSUE THREAD

**Issue by gangstead** [scala-ide/scalariform#130]
There are currently 65 issues and 18 PRs and no commits for more than a year.  I know anyone can fork it, and 81 people have, but it'd be nice to have the original scalariform up to date instead of having to go shopping through all the forks.

I realize this project may not be a priority for you anymore, but could you add some collaborators so we can keep it up to date?

**Comment by ktoso** [comment]
A related information you may find useful is that the current "considered active" fork is Daniel's here: https://github.com/daniel-trinh/scalariform

Truth be told, both repositories suffer from many people wanting to contribute, and the maintainer being unable to keep up with it. It would be awesome if we could add more maintainers to either repository.

// cc @daniel-trinh

**Comment by gangstead** [comment]
I've seen @daniel-trinh's scalariform and I also see active forks from @jkinkead and @michalkowol among others.  There's also the fork that's distributed by @scala-ide, that's only somewhat stale.  If I have to piece together all the improvements from all of these forks I'll just have unformatted code instead.

In an ideal world all these contributions would get rolled up to this repo, maybe with the help of some other collaborators or by being transferred to an org like Typesafe, Scala or Scala-IDE to update them as the language changes.

@odersky is there any need for an "official" scala formatter?

**Comment by jkinkead** [comment]
I would love so much if there were an official formatter. I forked mine because both this one and @daniel-trinh's seemed dead.

We use this at [allenai.org](http://allenai.org/) to keep things consistent, and it's incredibly helpful for readability purposes, especially for novices.

**Comment by boggle** [comment]
Totally would love someone to pick up the ball on this, would like to use this in a project but am reluctant to hook a dormant / unmaintained project into our build.

**Comment by RichardBradley** [comment]
+1

**Comment by daniel-trinh** [comment]
I'd be happy to add contributors to my fork, since my time is limited for developing new features that I believe the community would find useful. Once we identify people who are interested, we can get a discussion going.

**Comment by RichardBradley** [comment]
> > A related information you may find useful is that the current "considered active" fork is Daniel's here: https://github.com/daniel-trinh/scalariform
>
> Is that official? 

It looks like it is official, as `daniel-trinh` has publish access to `org.scalariform` in maven central and sonatype. See the comments on https://github.com/daniel-trinh/scalariform/issues/55

@mdr -- would you consider adding a comment about that to the top of the README on this repos, to aid people who were not aware of the new home of `scalariform`?

Thanks,


Rich

**Comment by dragos** [comment]
If you open a PR agains this repo, with the desired changes to README I can merge it.

**Comment by RichardBradley** [comment]
I think this issue can be closed now, thanks.

(You could even close all open issues and direct people to reopen them at https://github.com/daniel-trinh/scalariform if they are still valid?)
