### ISSUE TITLE
Bug in nested function call formatting in the presence of method calls.

### ISSUE THREAD

**Issue by iphydf** [scala-ide/scalariform#133]
Scalariform formats code like this:

```
  val foo = Foo(
    Thing(
      0
    )
  )
```

which is good, but if you add a method call to Thing(), it formats like this:

```
  val foo = Foo(
    Thing(
    0
  ).bar
  )
```

which is inconsistent and ugly.

**Comment by godenji** [comment]
In latest scalariform with `DanglingCloseParenthesis -> Force` the formatting is preserved.

```
val foo = Foo(
  Thing(
    0
  ).bar
)
```
