### ISSUE TITLE
integration tests for major projects

### ISSUE THREAD

**Issue by fommil** [scala-ide/scalariform#153]
we need to ensure that only bugs have been fixed since 0.1.4 and no major reformattings have been introduced, otherwise teams using legacy versions of scalariform will be left behind.

**Comment by fommil** [comment]
akka and ensime-server both use scalariform, we could put them in `sbt scripted` tests (as git subtrees) like we do in https://github.com/ensime/ensime-sbt/tree/master/src/sbt-test/ensime-sbt

**Comment by fommil** [comment]
(we can subtree merge the project, roll it back to use v0.1.4 of scalariform if its on a more recent version, format, commit and then set up the tests to use the included version of scalariform).

**Comment by sschaef** [comment]
Can sbt scripted override sbt dependencies? I ask because we need to run a nightly of scalariform and I wonder what is the best way to do so. Should we publish scalariform, then publish sbt-scalariform, then override the dependency in the projects, then run scalariform and then check if git sees any changes?

**Comment by fommil** [comment]
yup! I think that's just a case of adding a line to the `plugins.sbt` to override the `libraryDependencies` although I think it can also go in a standalone file.

**Comment by sschaef** [comment]
ok, going to check this out then

**Comment by fommil** [comment]
@jkinkead anything you can do here to help @sschaef would be greatly appreciated. Are you familiar with sbt scripted?

**Comment by jkinkead** [comment]
I am somewhat familiar with scripted - I'll see if I have some time to devote to this later this week. It shouldn't be super hard.

**Comment by fommil** [comment]
That'd be amazing, thank you so much.

**Comment by sschaef** [comment]
Yeah, would be super awesome to get some help here. During this week I'm busy with shipping a new scala-ide release.

**Comment by jkinkead** [comment]
So, akka in particular is super-huge. I don't know how exactly you've done these project dependencies in the past, but I see a few options:

1. Copy the full tree and commit it in one commit. This seems to be what you've done in `ensine-sbt`?
2. Copy just the scala source files, mimicking the directory structure.
3. `git clone` the project in the scripted test.
4. Use a git submodule.

1 & 2 have the advantage of being super-easy to get started, but have the disadvantage of being something that needs maintaining over time.

3 has the advantage of being up-to-date and super-easy to implement. It has the disadvantage of being incredibly slow.

4 has the advantage of being faster than 3 and easier-to-maintain than 1 & 2, but has the disadvantage of being a PITA to get working on a CB system.

I'll experiment with option 2 unless you think a different one would be better. For comparison, akka's whole repository is about 224M, while the scala files are about 10.5M.

**Comment by fommil** [comment]
I use git subtree merge in ensime-sbt. Works well.

**Comment by fommil** [comment]
But yeah, maybe a shallow clone of a specific commit is more appropriate here.

**Comment by jkinkead** [comment]
One more wrinkle I noticed last night: Akka is [currently using](https://github.com/akka/akka/blob/master/project/plugins.sbt#L14) the [1.2 release](https://github.com/sbt/sbt-scalariform/tree/ea52bb1ff19124e1fe63679ab35ba5fa8c615f81) of sbt-scalariform, which depends on v0.1.1 of scalariform itself. That version doesn't seem to be tagged, but it predates many changes and fixes in the `daniel-trinh` fork that have since been integrated into this fork.

What this means is that there's quite a bit of formatting churn due to older changes.

So, with the 2.0 release, what's the compatibility goal? Specifically, what's the version 2.0 should be backwards-compatible with?

**Comment by fommil** [comment]
Compatibility on the most part with pre-daniel fork.

**Comment by fommil** [comment]
You can always run the latest pre-daniel fork on akka and commit the changes.

**Comment by ktoso** [comment]
We're happy to upgrade but I'm currently not up to date which version would be best to jump to.
One commit of "moves around all the things because or new scalariform" is bearable, if after that the compatibility is indeed a goal :)

**Comment by fommil** [comment]
It doesn't need any change from akka, we'd pull whatever big projects we want to use in as git subtrees. They are being used as canaries for corporate projects, we don't really care about breaking things for akka per-se.

**Comment by fommil** [comment]
(What you suggested "one big commit" is absolutely NOT an option for most corporate projects I know of, and this is delaying IDE upgrades)

**Comment by jkinkead** [comment]
The assumption, then, is that the bigger project will *not* have upgraded to the newer `org.scalariform` scalariform, but will still be on the old `com.typesafe.sbt` scalariform?

This is going to punish adopters of the newer scalariform branch, which likely includes anyone who's come into scalariform in the past year or so.

Maybe it would be better to have two migration paths, one with backwards-compatibility with `daniel-trinh` and one with backwards-compatibility with `typesafe`? Having to throw an extra `sbt` configuration in when bumping up the scalariform version doesn't seem too bad . . .

**Comment by fommil** [comment]
yes, but those people can set the options, right? We could offer three settings:

- default (backwards compatible with pre-daniel, never changes except for corner case bugs)
- daniel-compatible (deprecated, will be removed)
- recommended (for the win!)

FYI, I'll be using "recommended" in ENSIME ;-) but do not underestimate the sheer force behind "default"

**Comment by jkinkead** [comment]
Perfect, SGTM.

Hiding some of the daniel changes behind options may be difficult. I'll file bugs for the kinda-regressions as I identify them.

**Comment by fommil** [comment]
the point of the regressions is to identify how big the impact is. If it turns out that a feature in daniel's branch only impacts 5 cases in all the projects we test, fine, we can live with that. But if its every file, then it needs an option.

**Comment by jkinkead** [comment]
Awesome.

There's one change I have in my sights that impacts virtually all files - it bit us when we upgraded about a year ago. There was a refactor in how multi-line method invocations were formatted, and most of them end up changed. I need a few repro cases before I can file an actionable bug, though.

**Comment by fommil** [comment]
aah, good old dangling new lines.

**Comment by fommil** [comment]
probably play and spray should be in there too. Spray routes are prone to reformatting regressions (you'll see some of that in ensime).

**Comment by jkinkead** [comment]
How do you feel about me opening issues tracking the compatibility changes? Some are really easy (`spacesAroundMultiImports` needs its default setting swapped), but others are trickier.

**Comment by sschaef** [comment]
Sure, go ahead.

**Comment by jkinkead** [comment]
I'm going to open a couple small PRs restoring default settings to what they were pre-v0.1.6. Let me know if that's going to be a problem.

**Comment by fommil** [comment]
Add them to the 1.0 milestone. There is so much noise.
