### ISSUE TITLE
Scalariform reformats code such that line length is way too long

### ISSUE THREAD

**Issue by sschaef** [scala-ide/scalariform#157]
_From @JohnDilley on January 6, 2016 20:9_

The results of formatting with Scalariform result in line lengths too long to pass scalastyle checks.  Either the formatting needs to be more intelligent, or if the reformatted line is longer than some reasonable value, then the code is left unchanged to avoid breaking automated scalastyle checkers.

Example:

```
class CompanyAdapterImpl extends Loggable with ConnectivityAdapter {
this: CompanyAccessor
  with PartnerServiceEnvironmentSettingsComponent
  with DomainActivityAccessor
  with DomainSaleAccessor
  with DomainSupplierConnectivityAccessor
  with DomainDirectConnectAccessor =>
```

is reformatted to

```
class CompanyAdapterImpl extends Loggable with ConnectivityAdapter {
this: CompanyAccessor with PartnerServiceEnvironmentSettingsComponent with DomainActivityAccessor with DomainSaleAccessor with DomainSupplierConnectivityAccessor with DomainDirectConnectAccessor =>    
```

_Copied from original issue: daniel-trinh/scalariform#106_

**Comment by felixt-cake** [comment]
It would be great if there were a way to change this behavior.  I use a very large font due to having poor eyesight, and the lack of configurability about max line length slows down my workflow a bit

**Comment by fedragon** [comment]
are there any updates on this? I'm used to working with two vertically-tiled windows (editor + sbt running in terminal) and having a maximum line length of 80-100 characters is crucial for code readability

**Comment by godenji** [comment]
@fedragon  `scalafmt` is probably your best bet for a line length enforced formatter. Short of a community contributed PR it's unlikely that this feature will make its way into Scalariform.

**Comment by fedragon** [comment]
ah I see, thanks!

**Comment by godenji** [comment]
With 0.2.4 you can stack param groups, which solves most line length issues (but not the OP's self type example)
```
def foo[T]
  (a: A)
  (b: B)
  (implicit t: T)
```

**Comment by RONNCC** [comment]
Is there any possibility for this to be added still ?

**Comment by godenji** [comment]
@RONNCC 

As mentioned in October:
> Short of a community contributed PR it's unlikely that this feature will make its way into Scalariform.

So if somebody has the time to implement a PR, it will be merged (I'm completely swamped in the near-term).
