### ISSUE TITLE
Provide option to indent method parameters at level of method

### ISSUE THREAD

**Issue by sschaef** [scala-ide/scalariform#158]
_From @nairbv on January 1, 2016 18:27_

When using the option -danglingCloseParenthesis=Preserve, the code:

```
def foobar(a:Int,
           c:Int,
           b:String) = {
  "hi"
}
```

Is reformatted to:

```
def foobar(
  a: Int,
  c: Int,
  b: String) = {
  "hi"
}
```

It would be nice if there were some way to preserve the method-level alignment.  If there's a new-line after the first open parenthesis, the code should be reformatted as in the example, but if not, I would think the parameters should be aligned to the indentation of the previous parameters (the level of the open-paren).

_Copied from original issue: daniel-trinh/scalariform#105_

**Comment by jkinkead** [comment]
The new preference in PR #205 allows for this.
