### ISSUE TITLE
Force 4 spaces for constructor args and 2 for extends

### ISSUE THREAD

**Issue by sschaef** [scala-ide/scalariform#160]
_From @ms-ati on December 23, 2015 1:10_

The option `doubleIndentClassDeclaration` doesn't do what I would expect, when it says that it meets the [scala styleguide description](http://docs.scala-lang.org/style/declarations.html)

> ...put each constructor argument on its own line, indented **four** spaces:

and

> ...then indent **four** spaces with each item being on its own line and **two** spaces for extensions; this provides visual separation between constructor arguments and extensions.:

In contrast, the current option appears to always indent the constructor arguments **two** spaces and then confusingly indents the extensions to **four** spaces, which seems to be the reverse of the style guide, and looks weird.

_Copied from original issue: daniel-trinh/scalariform#103_

**Comment by godenji** [comment]
@igormoreno in latest version of scalariform you can use `doubleIndentConstructorArguments` in place of `doubleIndentClassDeclaration`.
