### ISSUE TITLE
BUG: not possible to set `defaultScalariformSettings` in default settings

### ISSUE THREAD

**Issue by sschaef** [scala-ide/scalariform#162]
_From @fommil on December 6, 2015 15:5_

`override val settings = super.settings ++ defaultScalariformSettings`

in a `.scala` style project will result in missing tasks. It would be useful if this was allowed.

_Copied from original issue: daniel-trinh/scalariform#95_

**Comment by sschaef** [comment]
_From @daniel-trinh on December 6, 2015 21:38_

Is this with sbt-scalariform?

**Comment by sschaef** [comment]
_From @fommil on December 6, 2015 21:50_

yup, I think its a `Configuration` scope thing. Not a big deal because it can be worked around by adding the settings to each `Project`.

**Comment by godenji** [comment]
Should be fixed in latest `sbt-scalariform` (1.8.1)
