### ISSUE TITLE
Ability to list deviations from style.

### ISSUE THREAD

**Issue by sschaef** [scala-ide/scalariform#164]
_From @farmdawgnation on November 10, 2015 22:26_

I'm not sure the best way to ask this question, so I'm going to create an issue and if that's the wrong thing to do then you folks can come at me with the pitchforks.

I'm interested in the ability to have scalariform list out issues that it finds without formatting the entire file. So, for example, I could have a post-commit hook on my local machine that invokes Scalariform in "pretend" mode and have it list out formatting issues it finds in the files in that commit. Then I have the option of manually executing format on them in a separate commit or punting altogether.

I scanned the issue titles that already exist, but is there any plan to add support for something like this?

_Copied from original issue: daniel-trinh/scalariform#90_

**Comment by sschaef** [comment]
_From @daniel-trinh on December 7, 2015 7:43_

Couldn't you simply add code to the post-commit hook logic that discards changes in the case of not wanting the formatting, and exclude that step if you do want the formatting?

**Comment by sschaef** [comment]
_From @farmdawgnation on December 8, 2015 4:5_

I could, but I'm arguing that a "pretend" mode is something that should be a first class feature of the library anyway. Perhaps you disagree... if so then I guess we're at an impasse. But trying to get a sense for how many changes scalariform would want to make to my code before it actually makes them seems desirable to me in its own right.

**Comment by godenji** [comment]
Closest I can think of is to use [scalariform-cli](https://github.com/scala-ide/scalariform/wiki/Command-line-tool) with `--stdout` option to simulate a dry run.
