### ISSUE TITLE
options to align case statements and variable definitions

### ISSUE THREAD

**Issue by sschaef** [scala-ide/scalariform#170]
_From @fommil on August 30, 2015 14:53_

currently scalariform only supports aligning single line case statements, eg.

``` scala
case foo: Foo => ...
case bar         => ...
```

but it would be good if there was an option for multi line cases and also if there was a similar thing for variable definitions. At the very least, an option not to reformat the location of the `=` for variable definitions would be good.

_Copied from original issue: daniel-trinh/scalariform#76_

**Comment by godenji** [comment]
Duplicate of #70
