### ISSUE TITLE
Allow sorting of imports

### ISSUE THREAD

**Issue by sschaef** [scala-ide/scalariform#175]
_From @prettynatty on June 4, 2015 15:34_

It would be great to be able to sort imports using scalariform.
Without automatic imports sorting teams are suffering from merge conflicts and unorganized imports mess.

There is the same issue in old project: mdr/scalariform#67.

_Copied from original issue: daniel-trinh/scalariform#66_

**Comment by sschaef** [comment]
_From @magnusart on October 3, 2015 9:50_

+1 I really miss this. 
In addition warnings could be produced for unused import, that would be super helpful.

**Comment by sschaef** [comment]
_From @johnhanks1 on November 16, 2015 22:25_

+1 This would be great!

**Comment by sschaef** [comment]
_From @ngbinh on November 18, 2015 0:37_

+1

**Comment by sschaef** [comment]
_From @cristipp on November 18, 2015 16:49_

+1

**Comment by jkinkead** [comment]
Note that this requires a full parser, as scala imports can be relative.
```scala
// Not sortable without understanding the full symbol table.
import scala
import collection
import mutable
```

**Comment by cristipp** [comment]
To be fair, some projects use only absolute imports, so scalariform could help those, possibly under an option.

**Comment by fommil** [comment]
I think this should be closed as the feature is best implemented in `scala-refactoring`.

**Comment by sschaef** [comment]
On 02/18/2016 11:57 PM, Sam Halliday wrote:
>
> I think this should be closed as the feature is best implemented in 
> |scala-refactoring|.
>
I agree, scala-refactoring already supports that feature. Only problem 
is that it doesn't provide a cmd interface. If someone wants to work on 
this, they should work on the cmd interface for scala-refactoring.
