### ISSUE TITLE
AlignParameters: Missing space between colon and type when special characters are used 

### ISSUE THREAD

**Issue by sschaef** [scala-ide/scalariform#182]
_From @daniel-trinh on June 8, 2014 17:30_

When alignParameters is enabled, the colon between the name and type sometimes does not preserve the extra space after the type.

Failing test case:

``` scala
  """def a(
    |  underscore_ : Int = 1,
    |  underscore2__ : String = "1"
    |)""" ==>
  """def a(
    |  underscore_ :   Int    = 1,
    |  underscore2__ : String = "1"
    |)"""
```

Currently, the above example gets reformatted as this:

``` scala
def a(
  underscore_ :  Int    = 1,
  underscore2__ :String = "1"
)
```

Note the lack of space between the type and colon.

_Copied from original issue: daniel-trinh/scalariform#21_

**Comment by godenji** [comment]
As of latest scalariform with `SpaceBeforeColon -> true` the sample code formats as expected:

```
def a(
  underscore_ : Int = 1,
  underscore2__ : String = "1"
)
```
