### ISSUE TITLE
support format ArrowAssoc similar to alignSingleLineCaseStatements

### ISSUE THREAD

**Issue by sschaef** [scala-ide/scalariform#184]
_From @giabao on March 21, 2014 7:42_

``` scala
val m = Map(
  "a" -> 1,
  "bb" -> 2,
  "ccc" -> 3
)
```

is formatted as:

``` scala
val m = Map(
  "a"   -> 1,
  "bb"  -> 2,
  "ccc" -> 3
)
```

_Copied from original issue: daniel-trinh/scalariform#17_

**Comment by sschaef** [comment]
_From @acjay on July 14, 2015 18:17_

This would be great for overall consistency

**Comment by ches** [comment]
It seems either this or #109 can be closed as a duplicate.

**Comment by godenji** [comment]
Duplicate of #109
