### ISSUE TITLE
Automatic line breaking

### ISSUE THREAD

**Issue by gneuvill** [scala-ide/scalariform#19]
Hi,

Would it be possible to add an automatic line breaking behaviour to scalariform, along with the possibility to specify a number of characters at which the breaking should occur (default to 80) ?

Thanks,

Grégoire Neuville.

**Comment by adampauls** [comment]
+1

**Comment by RichardBradley** [comment]
+1

**Comment by godenji** [comment]
For automatic line breaking see the *scalafmt* library.
