### ISSUE TITLE
First argument / parameter gets a newline

### ISSUE THREAD

**Issue by jkinkead** [scala-ide/scalariform#202]
This behavior is new in the 0.1.6 / 0.1.7 fork, and should be fixed in milestone 1.0 per #142.

When argument or parameter lists span multiple lines, the first argument or parameter gets put on a newline. This is a bug introduced with the enhanced `AlignParameters` and `AlignArguments` settings.

Example code that would be reformatted from:
```scala
def foo(a: Int,
  b: Int
): Unit = {
  bar("arg1",
    "arg2"
  )
}
```
to:
```scala
def foo(
  a: Int,
  b: Int
): Unit = {
  bar(
    "arg1",
    "arg2"
  )
}
```
This is a big source of churn in codebases upgrading Scalariform.

**Comment by jkinkead** [comment]
I almost have a patch for this which introduces two new ternary settings similar to `danglingCloseParenthesis`. The default can then be updated to `Preserve` (the default pre-v0.1.6).

**Comment by jrudolph** [comment]
If this would be fixed it would prevent most of the changes necessary when upgrading akka to a recent version of scalariform (btw, are you just trying this as well?). See https://github.com/akka/akka/pull/19936.

**Comment by jkinkead** [comment]
The plan for scalariform v1.0 is to have only bugfix changes introduced when upgrading from the last pre-fork version, from what I understand.

This behavior is the biggest introducer of changes that can't be overridden with a preference, which is why I'm adding preferences for these.

I'm currently testing a bit against akka as a pre-0.1.6 benchmark (it's using v0.1.4 of scalariform).

**Comment by jrudolph** [comment]
Sounds good!

**Comment by jkinkead** [comment]
Ping @fommil / @sschaef on marking this milestone 1.0?

**Comment by fommil** [comment]
@sschaef can you please add @jkinkead as an admin?

**Comment by jkinkead** [comment]
Awesome, thanks for adding!

Any guidelines I should follow around code reviews / merging PRs, closing bugs, etc? I like having someone look over code before it's merged, but I also don't want to put any extra strain on your time.

Also, any mailing lists that would be useful to join?

**Comment by sschaef** [comment]
I'm going to have a look at all your PRs regarding review and merging in a few days. We are still not finished with shipping a new Scala IDE release and that is more important right now. We don't have special communication channels for scalariform yet. For now we use the scala-ide/scala-ide gitter room for all communication in the scala-ide organization.

**Comment by jkinkead** [comment]
Awesome, thanks for the update! I'll mark any PRs with the 1.0 milestone that I figure should go in.
