### ISSUE TITLE
Parser cannot parse val named `->`

### ISSUE THREAD

**Issue by sschaef** [scala-ide/scalariform#203]
_From @jrudolph on March 1, 2016 15:31_

You can see this when running `scalariformFormat` on akka/akka#19936:

```
[warn] Scalariform parser error for akka-actor/src/main/scala/akka/actor/FSM.scala: illegal start of simple pattern: Token(RARROW,->,11268,->)
```

_Copied from original issue: daniel-trinh/scalariform#113_

**Comment by jrudolph** [comment]
Thanks, @sschaef. Didn't get it that there's still another repo for scalariform ;)

**Comment by jrudolph** [comment]
Is the rewriting of `->` documented somewhere? It's not safe. It works only if an occurence happens to reference `ArrowAssoc.->` which also has `ArrowAssoc.→` defined. This is not given for the above file (Akka's FSM) in which case formatting actually breaks things (see https://github.com/akka/akka/pull/19936#issuecomment-190780990).

**Comment by fommil** [comment]
@sschaef can you close the issue tracker on daniel's repo?

**Comment by sschaef** [comment]
No, don't have the permissions. We probably shouldn't even close it because the moment when it is closed, we can't access existing tickets anymore. Not sure if there is any important stuff in there. The moment when we announce that the upstream project is back to live most people know that they no longer should create tickets at Daniels fork. And Google already knows about us, for new users it is already a no issue.

**Comment by sschaef** [comment]
I think `->` being rewritten is a feature that was introduced in Daniels fork. It definitely needs to be disabled by default.

**Comment by isomarcte** [comment]
I just hit this bug using the dsl in http4s which defines `->`.

Is there a reason that `->` is treated specially at all? I.e. why is it parsed as `RARROW` and not just `VARID`? I check the language spec and the only reference I saw was to the global implicit def for `Tuple2`.

**Comment by daniel-trinh** [comment]
I believe I merged an MR that added this feature with the assumption that there wouldn't be other's redefining `->`, which explains the bug people are seeing. 

In light of that discovery, I'd agree it makes sense to disable this behavior, or at least modify it to support any usage of `->`

**Comment by jkinkead** [comment]
It's the `rewriteArrowSymbols` flag that controls this; it's not on by default.

The rewriting should probably be removed entirely, since it's a library function and not a language feature. I'll open a separate bug to track disabling this - the parse error is a separate thing.

**Comment by jrudolph** [comment]
> The rewriting should probably be removed entirely, since it's a library function and not a language feature.

Yes, exactly. The rewriting is ok for `=>` which is a syntactical feature of Scala, however, for `->` the formatter would need semantical information to figure out whether the rewriting is ok.
