### ISSUE TITLE
Push tags for releases

### ISSUE THREAD

**Issue by jrudolph** [scala-ide/scalariform#207]
According to https://github.com/scala-ide/scalariform/releases 0.1.7 was the latest version. Would be nice if tags would be pushed for all versions :)

**Comment by sschaef** [comment]
Which tags are missing. I can see all of them.

**Comment by jrudolph** [comment]
Isn't there 0.1.8 and 0.2.0 by now?

**Comment by sschaef** [comment]
0.1.8 was the version of the nightly of Daniels fork. It never was released. 0.2.0 is the current nightly version.

**Comment by jrudolph** [comment]
Mmh... but 0.1.8 is the version that sbt-scalariform uses: https://github.com/sbt/sbt-scalariform/blob/master/project/Dependencies.scala#L4

**Comment by sschaef** [comment]
Alright, there was a 0.1.8 branch on Daniels fork. I guess its latest version is the one that was used by sbt-scalariform. I just added a tag for it.
