### ISSUE TITLE
`rewriteArrowSymbols` shouldn't reformat `->`

### ISSUE THREAD

**Issue by jkinkead** [scala-ide/scalariform#209]
`rewriteArrowSymbols` replaces `->` with `→`, which isn't a safe operation.

This should either be removed or placed behind a separate flag.

**Comment by s-nel** [comment]
It's also not in the documentation that this 

> Replace arrow tokens with their unicode equivalents: => with ⇒, and <- with ←

Further, the release notes say

> Rewrite -> into → when RewriteArrowSymbols is on (issue #34)

Issue #34 isn't even related!

**Comment by daniel-trinh** [comment]
The issue number was relative to when the repo was on my fork. I suppose it would make sense to go through the release notes and append which fork the issue numbers are for. https://github.com/daniel-trinh/scalariform/issues/34

**Comment by jkinkead** [comment]
This was fixed in #210 .
