### ISSUE TITLE
homebrew install doesn't install from this repo

### ISSUE THREAD

**Issue by vikasuy** [scala-ide/scalariform#229]
It looks like its pointing to the old repo:
http://brewformulas.org/scalariform

**Comment by jkinkead** [comment]
I have no idea how to go about fixing this. I'm not even sure homebrew formula was created by a scalariform maintainer.

I'll leave this open in case anyone wants to jump in and fix.

**Comment by godenji** [comment]
Should work now, homebrew points to the [latest release](https://github.com/Homebrew/homebrew-core/blob/master/Formula/scalariform.rb)
