### ISSUE TITLE
upgrade to ScalaTest 3.0?

### ISSUE THREAD

**Issue by SethTisue** [scala-ide/scalariform#232]
we would very much like to add scalariform back to the Scala 2.12 community build (it has been commented out for a long time), but in order for that to happen, you'd need to move to ScalaTest 3.0, which is the only version we support in the community build

Bill & co are pretty militant about providing smooth migration paths, so I assume it wouldn't be very hard, though possibly tedious. I did try simply bumping the version number, but there were compile errors.

**Comment by fommil** [comment]
is this also blocking releasing for 2.12?

**Comment by SethTisue** [comment]
Scalariform is back in the 2.12 community build now, but we aren't able to compile or run its tests. It would be better if we could.

**Comment by godenji** [comment]
> upgrade to ScalaTest 3.0?
> support Scala 2.12

Done

> "org.scalariform" %% "scalariform" % "0.2.0"

**Comment by SethTisue** [comment]
@godenji awesome! scala/community-builds@12144742518e83798572eefe8caa990233b3cd1c enables the tests again

**Comment by godenji** [comment]
> scala/community-builds@1214474 enables the tests again

@SethTisue cool, good to hear ;-)

Just [issued a PR](https://github.com/scala-ide/scala-ide/pull/1171) to Scala IDE that brings embedded `scalariform` up-to-date with latest published version. Make Scala tooling great again! (or at least somewhat cohesive/working).
