### ISSUE TITLE
Release 2.12 version

### ISSUE THREAD

**Issue by matthewfarwell** [scala-ide/scalariform#235]
Could we have an official 2.12 version please?

**Comment by dwijnand** [comment]
I have a related Scalariform question: must there be a 2.12 release to format Scala 2.12 code? For example there is no 2.10 or 2.12 version of Scala.meta, yet it can parse and understand 2.10/2.11/2.12, even Dotty code. Thanks.

**Comment by matthewfarwell** [comment]
Technically correct.

However, with the trailing commas this is no longer the case.

And if the rest of your toolchain is using 2.12, then it would be nice to have a 2.12 scalariform & scalastyle.

**Comment by sschaef** [comment]
Please note, this repo is no longer maintained. Any pull requests would not get any attention.

**Comment by matthewfarwell** [comment]
Does that mean that there won't be any more releases? Should I fork an do it myself?

**Comment by sschaef** [comment]
the latest master is not compatible functionality wise to the latest available release. So, no there won't be new releases because there is no one who wants to restore backwards compatibility. However, I released a 2.12 version of the latest available public release, but that one is only used by scala-ide internally.

**Comment by sschaef** [comment]
I guess I can make the 2.12 version available to the public

**Comment by matthewfarwell** [comment]
That would be brilliant.

**Comment by cvogt** [comment]
Would be very interested in this as well :)

**Comment by fommil** [comment]
@sschaef "the latest master is not compatible functionality wise to the latest available release" what broke?

**Comment by sschaef** [comment]
I can't remember. You were there one who said that there were features that behave differently.

**Comment by fommil** [comment]
I honestly can't remember :-/

**Comment by cvogt** [comment]
FWIW, I am using the latest master for CBT, recently switching from 0.1.8. I am only formatting < 1K LOC at the moment, but in those everything is the same, except bug https://github.com/scala-ide/scalariform/issues/240 is **fixed** in master but not in 0.1.8. I am using these settings https://github.com/cvogt/cbt/blob/d6245c8dc5c7b2f885d538b39f685327da252863/plugins/scalariform/Scalariform.scala

**Comment by fommil** [comment]
so long as `master` is backwards binary compatible with the released version, it's good for me.

**Comment by cvogt** [comment]
ok, I now realized current master doesn't exactly fix the bug I mentioned. It just moved the problem somewhere else.

This improves from 0.1.8 to master (there was too little indentation)
```
     f.copy(
       function = (
-      ( args: Seq[String] ) => f.function( args.to )
-    )
+        ( args: Seq[String] ) => f.function( args.to )
+      )
     )
   }
```

This degrades from 0.1.8. to master (there now is too much)
```

**Comment by cvogt** [comment]
Mh, actually trying the commit tagged with `0.1.8` yield the same result as master (and built with 2.11.8), but a different result than the sbt plugin using the maven released 0.1.8.

(We should probably discuss this in a different ticket)

**Comment by fommil** [comment]
@taig seems to have been releasing his own builds of scalariform... although I'm not sure what's in them. Perhaps he would be interested in taking more of a role maintaining this version of the repo? I wouldn't mind having a 0.2.0 release to upgrade to with the newer features. Now that the split artifact issue is solved (although `taig` seems to be intent on starting it all over again...) people can opt-in to the versions.

**Comment by godenji** [comment]
> Release 2.12 version

Done

> "org.scalariform" %% "scalariform" % "0.2.0"

**Comment by matthewfarwell** [comment]
Great. Thanks!
