### ISSUE TITLE
spacesAroundMultiImports needs a third option import foo.{a, b} (vs foo.{ a, b } or foo.{a,b})

### ISSUE THREAD

**Issue by er1c** [scala-ide/scalariform#239]
I just tried running scalarform on one of our first packages and this was one of the first formatting "errors" I'm trying to get around.

I want support for `import foo.{a, b}`, but the only two options appear to be `import foo.{ a, b }` or `import foo.{a,b}`

Almost every scala project I've worked with uses `{a, b}` - with spaces inside, but no spaces next to the curly brackets.

Here are a few other example Projects like `scala` and `scala-js`

https://github.com/scala-js/scala-js/search?utf8=%E2%9C%93&q=import

https://github.com/scala-js/scala-js/blob/7640e858efbf8dbf52c99ca8a82cfb2350836e02/compiler/src/test/scala/org/scalajs/core/compiler/test/MatchASTTest.scala#L8
https://github.com/scala-js/scala-js/blob/7640e858efbf8dbf52c99ca8a82cfb2350836e02/test-suite/js/src/test/scala/org/scalajs/testsuite/niobuffer/ByteBufferJSFactories.scala#L9

https://github.com/scala/scala/search?utf8=%E2%9C%93&q=import

https://github.com/scala/scala/blob/05016d9035ab9b1c866bd9f12fdd0491f1ea0cbb/test/files/pos/imports-pos.scala#L6

**Comment by er1c** [comment]
Unfortunately, the scala docs.scala-lang.org/style/ doesn't appear to have any guidance here.  The `{<nospace>a, b<nospace>}` is consistent with typeclass formatting `[A, B]`

**Comment by er1c** [comment]
I added a (token) $15 bounty for this https://www.bountysource.com/issues/41023979-spacesaroundmultiimports-needs-a-third-option-import-foo-a-b-vs-foo-a-b-or-foo-a-b

**Comment by amanjpro** [comment]
It seems nobody is working on this, I will give it a shot today and see what will happen

**Comment by amanjpro** [comment]
It turned out that the documentation is wrong, this feature actually exists. Have you tried it?

**Comment by amanjpro** [comment]
I believe that the documentation should mention that the behaviour of `scalariform` is to add a space after commas, arrows and other similar tokens.

**Comment by er1c** [comment]
@amanjpro sure!

Here's an example of after running scalariform:
```
-import scala.collection.convert.{DecorateAsJava, DecorateAsScala}
+import scala.collection.convert.{ DecorateAsJava, DecorateAsScala }
```

Ideally this wouldn't be changed to add the additional spaces after the `{` and `}` for my use case

**Comment by er1c** [comment]
Innnteresting, I just ran the `spacesAroundMultiImports ` with false again 

and it did go back to `import scala.collection.convert.{DecorateAsJava, DecorateAsScala}`

**Comment by er1c** [comment]
As a test I also tried: `import scala.collection.convert.{ DecorateAsJava,DecorateAsScala }` and it reformatted it to `import scala.collection.convert.{DecorateAsJava, DecorateAsScala}` which is exactly what I want.  If you want to do a PR to update the docs/example in the https://raw.githubusercontent.com/scala-ide/scalariform/master/README.rst, I'd be happy to award you the beer money bounty :)

**Comment by amanjpro** [comment]
What version do you run? I implemented it only to figure out that is already the case in master branch

**Comment by amanjpro** [comment]
If you want I can push my changes to my fork and try it

**Comment by er1c** [comment]
@amanjpro if you just want to update that README file and add that as another pull request, I'd be happy with that!

**Comment by amanjpro** [comment]
That is really strange, I just tried it again and it works as expected, this time used the `sbt` plugin version `1.6.0`. Can you tell me which versions did you try? If you have used the one bundled within the maven plugin, then it is a few versions behind.

As for the documentation, it is in my TODO list.

BTW, I sat `spacesAroundMultiImports` to false

**Comment by amanjpro** [comment]
Here is where it is done: https://github.com/scala-ide/scalariform/blob/master/scalariform/src/main/scala/scalariform/formatter/ScalaFormatter.scala#L344

**Comment by er1c** [comment]
I'm all confused now,  I'm using `addSbtPlugin("org.scalariform" %
"sbt-scalariform" % "1.6.0")`

**Comment by amanjpro** [comment]
This is really interesting, can you send me your scalariform setting in SBT?

**Comment by er1c** [comment]
```
    // Default Scalariform settings
    ScalariformKeys.preferences := ScalariformKeys.preferences.value
            .setPreference(AlignSingleLineCaseStatements, true)
            .setPreference(DoubleIndentClassDeclaration, true)
            .setPreference(CompactStringConcatenation, true) // "Hello " + name + "!" => "Hello "+name+"!"
            .setPreference(PreserveDanglingCloseParenthesis, true)
            .setPreference(SpacesAroundMultiImports, false)
```

**Comment by amanjpro** [comment]
What happens if you only have the last one and delete the other ones?

**Comment by er1c** [comment]
Using:

```
    // Default Scalariform settings
    ScalariformKeys.preferences := ScalariformKeys.preferences.value
            .setPreference(SpacesAroundMultiImports, false)
```

I still get:

`import scala.collection.convert.{DecorateAsJava, DecorateAsScala}` so I think that's good

**Comment by amanjpro** [comment]
Great. I'll try to find out the mystery setting that does this as side effect and will fix it.
