### ISSUE TITLE
Import scala.collection.immutable.Seq

### ISSUE THREAD

**Issue by kag0** [scala-ide/scalariform#251]
A handy feature would be to add an import for `scala.collection.immutable.Seq` any time the `Seq` predef is used, unless `scala.collection.Seq` or `scala.collection.mutable.Seq` is already imported.

This would probably be disabled by default, but would be very handy for people who want to enforce immutable `Seq`s.

A useful example: 
```scala
case class MyCaseClass(strings: Seq[String])
```
would become
```scala
scala.collection.immutable.Seq

case class MyCaseClass(strings: Seq[String])
```
 We typically expect our case classes to be immutable, preventing a missed import from leading to unexpected behavior from side-effects is a nice thing to have.

**Comment by godenji** [comment]
I think this issue will be resolved in Scala 2.13 (defaults to immutable Seq).

Also, out of scope, better suited to *scala-refactoring*
