### ISSUE TITLE
Feature Request: Mixed single-line and multi-line case statements

### ISSUE THREAD

**Issue by mjaghouri** [scala-ide/scalariform#252]
```
xxx match {
  case Complex =>
      // needs multiple 
      // lines
  case Other1   => // single line
  case Another2 => // single line
  case Other12  => // single line
}
```

If there are mixed single-line and multi-line case statements, I would like to align the arrow in the consecutive single lines still. Even with the `alignSingleLineCaseStatements` option now, it would even un-aligns my single line cases in the above example.

**Comment by godenji** [comment]
Seems to work in 0.2.4, closing (re-open if I've misunderstood the issue)

```
xxx match {
  case Complex  =>
  // needs multiple
  // lines
  case Other1   => // single line
  case Another2 => // single line
  case Other12  => // single line
}
```
