### ISSUE TITLE
Space after an equal sign in foreach statements is being removed

### ISSUE THREAD

**Issue by Jaystified** [scala-ide/scalariform#254]
`foo.foreach(bar.baz = _)`
Is being formatted into
`foo.foreach(bar.baz= _)`
I'd like to be able to have it the other way around...

**Comment by godenji** [comment]
Thanks for reporting, "gapless assignment" was fixed in 0.2.1, must have been a regression (or tests in `MutateTest.scala` don't cover this case).

This is especially annoying in Scala.js
