### ISSUE TITLE
trailing comma support - "Expected identifier, but got Token(RPAREN,),xxx,))

### ISSUE THREAD

**Issue by marekzebrowski** [scala-ide/scalariform#260]
linked issue with reproducer https://github.com/scalastyle/scalastyle/issues/276
even simpler example of valid scala 2.12 code
```
case class A(i:Int,
)
```
is not parsed correctly

**Comment by godenji** [comment]
For everyone who thumbs up'd this issue the [companion PR](https://github.com/scala-ide/scalariform/pull/262) won't get merged until there's some test coverage that verifies trailing commas work as expected (and don't break existing tests).

A simple test implementation might look [like this](https://github.com/scala-ide/scalariform/pull/262#issuecomment-343663890).

**Comment by c-dante** [comment]
I made a parser spec that the PR fails on -- working on a fix that supports http://docs.scala-lang.org/sips/completed/trailing-commas.html

**Comment by godenji** [comment]
fixed in #262
