### ISSUE TITLE
Cannot Undo after Formatting

### ISSUE THREAD

**Issue by robbyki** [scala-ide/scalariform#268]
Not sure why I get a cannot undo `Following Files have changes that cannot be undone` error after applying my formatting? I can't seem to be able to undo anything which would be a big problem for using scalariform. Tried on Intellij EAP and 2017.3.

**Comment by godenji** [comment]
Your best bet is to go with the *scalafmt* library; they have built-in IntelliJ support, IIRC.

**Comment by robbyki** [comment]
Thanks. that did the trick.
