### ISSUE TITLE
Allow single case on same line as what comes before

### ISSUE THREAD

**Issue by jppellet** [scala-ide/scalariform#29]
Sorry, my title is especially vague and uninformative. Here's an example.

<pre>
list.foreach { elem =>
  /* do something with elem */
}

list.foreach { case (key, value) => // (***)
  /* do something with elem */
}
</pre>

It would be great if there was an option to keep my standalone case on line **\* on the same line (currently it always wraps before "case"), to mimic the style for the non-tuple case, recommended by the Scala Style Guide. It would remove one useless level of indentation.

**Comment by godenji** [comment]
@jppellet More than 6 years after the fact this issue can now be closed -- exciting, no?

Probably not, but thanks for raising the issue regardless, a nice improvement.

**Comment by jppellet** [comment]
That's cool! Thanks!
