### ISSUE TITLE
Allow expression break after open paren

### ISSUE THREAD

**Issue by mdr** [scala-ide/scalariform#33]
_Ported from issue #32:_

Thank you for explaining, it's not an urgent need, but it would be nice if it were supported at some point. If you want to fix individual cases, then my biggest pain point is scalariform moving:

``` scala
(
  a_long_line &&
  b_long_line
)
```

to

``` scala
(a_long_line &&
   b_long_line)
```

which I find notpretty at all...

**Comment by godenji** [comment]
use `DanglingCloseParenthesis -> Force`
