### ISSUE TITLE
IntelliJ support

### ISSUE THREAD

**Issue by vjpr** [scala-ide/scalariform#35]
IntelliJ is an increasingly popular IDE for Scala. It would be fantastic to be able to synchronize IntelliJ's Scala Code Style settings so that when you `Reformat Code... (Ctrl+Alt+L)` it would replicate the settings you have configured in Scalariform.

A few approaches:

**IntelliJ External Code Formatter plugin** (last updated 2011-10-05 20:47:43)

http://plugins.intellij.net/plugin/?id=1605

**Generate IntelliJ code style XML definition and manually import**

You could have an export to IntelliJ feature that would prepare an XML code style definition to import into IntelliJ manually using `File > Import Settings...`

---

The https://github.com/typesafehub/sbt-scalariform SBT plugin works really well at the moment so I'm not sure if this support would be that useful.

**Comment by melodious** [comment]
This doesn't appear to work properly in Intelij 2016. I do not see Scalariform in the preferences at all. Is there a way to configure it in Intellij?

**Comment by godenji** [comment]
For the heathens that insist on using IntelliJ, we suggest using *scalafmt*, a next generation Scala formatting library (which shares one thing in common with *scalac*, glacial performance ;-))

Seriously though, it is unlikely that integration with IntelliJ will happen barring external projects like https://github.com/thesamet/scalariform-intellij-plugin (which was updated last October, so not too far out-of-date)
