### ISSUE TITLE
alignParameters doesn't align method calls

### ISSUE THREAD

**Issue by srp** [scala-ide/scalariform#53]
alignParameters works great for declarations, but for method calls i get:

    o.method(color = Red,
      size=1000,
      texture=Tacky)

rather then the what i'd expect with this option on:

    o.method(color = Red,
             size = 1000,
             texture=Tacky)

(where 'c', 's', and 't' are aligned vertically)

**Comment by jkinkead** [comment]
`alignArguments` parameter does this now.
