### ISSUE TITLE
"Preserve dangling close parenthesis" option does not seem to be working

### ISSUE THREAD

**Issue by curreli** [scala-ide/scalariform#75]
Please, see the following link:

https://www.assembla.com/spaces/scala-ide/support/tickets/1001528-scalarifom-option--preserve-dangling-close-parenthesis--is-not-working#/activity/ticket:

**Comment by fommil** [comment]
@daniel-trinh your branch's fix for this ticket works programmatically (i.e. when we call it from ENSIME) but not when invoked from sbt (i.e. formatting as part of the sbt build).

**Comment by fommil** [comment]
also, isn't this #98 ?

**Comment by jkinkead** [comment]
The `danglingCloseParenthesis` should have fixed any issues with this old option.
