### ISSUE TITLE
Allow forcing of multi line cases

### ISSUE THREAD

**Issue by AlecY** [scala-ide/scalariform#82]
for example 
val decl = symbol.scope match {
          case Local  => genLocalVariableDeclaration(symbol)
  }
should become
val decl = symbol.scope match {
          case Local  =>
            genLocalVariableDeclaration(symbol)
        }
This makes setting breakpoints in the eclipse debugger much simpler

**Comment by godenji** [comment]
Scalariform does not prevent writing the code as desired

```
val decl = symbol.scope match {
  case Local =>
    genLocalVariableDeclaration(symbol)
}
```
