### ISSUE TITLE
Ability to align arbitrary characters

### ISSUE THREAD

**Issue by nafg** [scala-ide/scalariform#84]
This is not so trivial, but it would nice to be able to tell scalariform to align lines in a dsl in various ways. For instance:

```
((xxxx, yy)          -> z),
((xx,y)                -> zzzz)

```

Or perhaps spacing things in custom ways. For instance in the Lift SiteMap DSL, you tag menus with directives with the >> method. So it would be nice instead of getting
Menu("a") / "b" / "c" >> Hidden >> If(...)
to get
Menu("a") / "b" / "c"  >>Hidden>  >>If(...)
(i.e., two spaces before >> and none after)
etc. etc.

Presumably you could only write such instructions in a comment directive. I guess there would have to be some DSL to express such things.

**Comment by nafg** [comment]
@godenji did this get implemented?

**Comment by godenji** [comment]
no, feel free to issue a PR though if you're interested in a such a feature.
