### ISSUE TITLE
Annotations format

### ISSUE THREAD

**Issue by gagnechris** [scala-ide/scalariform#91]
Currently when executing scalariform on a source file which includes annotations, the definition and annotation are put on the same line.  Can a parameter be introduced to turn this specific formatting off?

For example, here is why my code looks like before executing scalariform (2 lines):
@ApiModelProperty(value = "A description of the model property")
val modelProperty: Option[ModelPropertyInfo] = None,

Here is what the above code is changed to after executing scalariform (1 line):
@ApiModelProperty(value = "A description of the model property") val modelProperty: Option[ModelPropertyInfo] = None,

Thanks!

**Comment by patrikvarga** [comment]
+1, this is very annoying, especially that it is not conforming the Scala Style Guide and thus makes the following statement in the documentation invalid:
"Scalariform is compatible with the Scala Style Guide in the sense that, given the right preference settings, source code that is initially compiliant with the Style Guide will not become uncompliant after formatting."

**Comment by metasim** [comment]
+1

**Comment by godenji** [comment]
Seems to work with latest version of scalariform

```
@apimodelproperty(value = "A description of the model property")
val modelProperty: Option[ModelPropertyInfo] = None
```
