### ISSUE TITLE
Preserve dangling brackets in parameter lists

### ISSUE THREAD

**Issue by paddymahoney** [scala-ide/scalariform#98]
Take the class definition: 

case class User(id: Long, name: String, age: Int, address: String)

I would like to format this as : 

case class User(
  id: Long, 
  name: String, 
  age: Int, 
  address: String
)

When scalariform is run with 'Preserve dangling close parenthesis', it reformats this to: 

case class User(
  id: Long, 
  name: String, 
  age: Int, 
  address: String)

This feature is requesting an option so that when this case class is scalariformed, the bracket is not brought up to the preceeding line - either 'Preserve dangling close parenthesis' be made to apply to parameter lists in functions and classes, or a new option 'Preserve dangling closed parenthesis in classes and functions' be added.

**Comment by hzwaal** [comment]
+1

**Comment by joprice** [comment]
+1

**Comment by godenji** [comment]
use `danglingCloseParenthesis=Force` in scalariform 2.0+
